const SET_SINGER = 'SET_SINGER'

const SET_PLAYING = 'SET_PLAYING'

const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

const SET_PLAY_LIST = 'SET_PLAYING'

const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

const SET_MODE = 'SET_MODE'

const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export { 
    SET_SINGER,
    SET_PLAYING,
    SET_FULL_SCREEN,
    SET_PLAY_LIST,
    SET_SEQUENCE_LIST,
    SET_MODE,
    SET_CURRENT_INDEX
}