const SET_SINGER = 'SET_SINGER'

const SET_PLAY_STATE = 'SET_PLAY_STATE'

const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

const SET_PLAYLIST = 'SET_PLAYLIST'

const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

const SET_MODE = 'SET_MODE'

const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export { 
    SET_SINGER,
    SET_PLAY_STATE,
    SET_FULL_SCREEN,
    SET_PLAYLIST,
    SET_SEQUENCE_LIST,
    SET_MODE,
    SET_CURRENT_INDEX
}